addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/sneg.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'des_ripplsand')
engineApplyShaderToWorldTexture(shader, 'des_dirt1')
engineApplyShaderToWorldTexture(shader, 'des_rocky1_dirt1')
engineApplyShaderToWorldTexture(shader, 'des_scrub1_dirt1')
engineApplyShaderToWorldTexture(shader, 'des_scrub1')
engineApplyShaderToWorldTexture(shader, 'desstones_dirt1')
engineApplyShaderToWorldTexture(shader, 'des_dirt2dedgrass')
engineApplyShaderToWorldTexture(shader, 'des_dirt2')
engineApplyShaderToWorldTexture(shader, 'des_dirtgravel')
engineApplyShaderToWorldTexture(shader, 'des_dirt2blend')
engineApplyShaderToWorldTexture(shader, 'des_rocky1')
engineApplyShaderToWorldTexture(shader, 'des_roadedge1')
engineApplyShaderToWorldTexture(shader, 'des_roadedge2')
engineApplyShaderToWorldTexture(shader, 'des_panelconc')
engineApplyShaderToWorldTexture(shader, 'des_oldrunwayblend')
engineApplyShaderToWorldTexture(shader, 'desertstones256')
engineApplyShaderToWorldTexture(shader, 'grasstype5')
engineApplyShaderToWorldTexture(shader, 'grasstype5_dirt')
engineApplyShaderToWorldTexture(shader, 'grasslong256')
engineApplyShaderToWorldTexture(shader, 'desgreengrass')
engineApplyShaderToWorldTexture(shader, 'sw_grass01')
engineApplyShaderToWorldTexture(shader, 'sw_grass01a')
engineApplyShaderToWorldTexture(shader, 'yardgrass1')
engineApplyShaderToWorldTexture(shader, 'grasstype7')
engineApplyShaderToWorldTexture(shader, 'grassdeadbrn256')
engineApplyShaderToWorldTexture(shader, 'desgreengrassmix')
engineApplyShaderToWorldTexture(shader, 'desertgryard256')
engineApplyShaderToWorldTexture(shader, 'desgrassbrn')
engineApplyShaderToWorldTexture(shader, 'des_grass2scrub')
engineApplyShaderToWorldTexture(shader, 'des_scrub1_dirt1b')
engineApplyShaderToWorldTexture(shader, 'des_scrub1_dirt1a')
engineApplyShaderToWorldTexture(shader, 'bow_church_grass_gen')
engineApplyShaderToWorldTexture(shader, 'grassdead1')
engineApplyShaderToWorldTexture(shader, 'forestfloor256')
engineApplyShaderToWorldTexture(shader, 'forestfloorblendded')
engineApplyShaderToWorldTexture(shader, 'forestfloor256_blenddirt')
engineApplyShaderToWorldTexture(shader, 'grasstype10')
engineApplyShaderToWorldTexture(shader, 'grass10_stones256')
engineApplyShaderToWorldTexture(shader, 'grass10des_dirt2')
engineApplyShaderToWorldTexture(shader, 'grasstype510')
engineApplyShaderToWorldTexture(shader, 'grasstype510_10')
engineApplyShaderToWorldTexture(shader, 'grass10dirt')
engineApplyShaderToWorldTexture(shader, 'forestfloor256mudblend')
engineApplyShaderToWorldTexture(shader, 'ws_patchygravel')
engineApplyShaderToWorldTexture(shader, 'grasstype4')
engineApplyShaderToWorldTexture(shader, 'ws_traingravelblend')
engineApplyShaderToWorldTexture(shader, 'forestfloorgrass')
engineApplyShaderToWorldTexture(shader, 'des_dirt1grass')
engineApplyShaderToWorldTexture(shader, 'grasstype5_desdirt')
engineApplyShaderToWorldTexture(shader, 'des_dirt1')
engineApplyShaderToWorldTexture(shader, 'des_grass2dirt1')
engineApplyShaderToWorldTexture(shader, 'blendrock2grgrass')
engineApplyShaderToWorldTexture(shader, 'sfn_rocktbrn128')
engineApplyShaderToWorldTexture(shader, 'sfn_rockhole')
engineApplyShaderToWorldTexture(shader, 'sfn_grass1')
engineApplyShaderToWorldTexture(shader, 'grass_128hv')
engineApplyShaderToWorldTexture(shader, 'grassdead1blnd')
engineApplyShaderToWorldTexture(shader, 'desertgravelgrass256')
engineApplyShaderToWorldTexture(shader, 'grassbrn2rockbrn')
engineApplyShaderToWorldTexture(shader, 'greyground2sand')
engineApplyShaderToWorldTexture(shader, 'grassgrnbrn256')
engineApplyShaderToWorldTexture(shader, 'desertgryard256grs2')
engineApplyShaderToWorldTexture(shader, 'grasstype5_4')
engineApplyShaderToWorldTexture(shader, 'brngrss2stones')
engineApplyShaderToWorldTexture(shader, 'desgrassbrn_grn')
engineApplyShaderToWorldTexture(shader, 'desgrasandblend')
engineApplyShaderToWorldTexture(shader, 'hiwayinside4_256')
engineApplyShaderToWorldTexture(shader, 'ws_traingravel')
engineApplyShaderToWorldTexture(shader, 'hiway2sand1a')
engineApplyShaderToWorldTexture(shader, 'sw_traingravelb1')
engineApplyShaderToWorldTexture(shader, 'trainground2')
engineApplyShaderToWorldTexture(shader, 'sandnew_law')
engineApplyShaderToWorldTexture(shader, 'grasstype4_forestblend')
engineApplyShaderToWorldTexture(shader, 'grasstype4_mudblend')
engineApplyShaderToWorldTexture(shader, 'grass4dirtytrans')
engineApplyShaderToWorldTexture(shader, 'sw_sand')
engineApplyShaderToWorldTexture(shader, 'sw_sandgrass4')
engineApplyShaderToWorldTexture(shader, 'forestfloor_sones256')
engineApplyShaderToWorldTexture(shader, 'grasstype3')
engineApplyShaderToWorldTexture(shader, 'grasstype4-3')
engineApplyShaderToWorldTexture(shader, 'grass4_des_dirt2')
engineApplyShaderToWorldTexture(shader, 'cw2_mountdirt2grass')
engineApplyShaderToWorldTexture(shader, 'cw2_mountdirt')
engineApplyShaderToWorldTexture(shader, 'desertgravelgrassroad')
engineApplyShaderToWorldTexture(shader, 'des_dirtgrassmixbmp')
engineApplyShaderToWorldTexture(shader, 'des_dirtgrassmix_grass4')
engineApplyShaderToWorldTexture(shader, 'desertstones256forestmix')
engineApplyShaderToWorldTexture(shader, 'grasstype4blndtomud')
engineApplyShaderToWorldTexture(shader, 'ws_rooftarmac1')
engineApplyShaderToWorldTexture(shader, 'cw2_mountdirtscree')
engineApplyShaderToWorldTexture(shader, 'ws_coppersheet')
engineApplyShaderToWorldTexture(shader, 'ws_wetsand')
engineApplyShaderToWorldTexture(shader, 'ws_wetdryblendsand')
engineApplyShaderToWorldTexture(shader, 'ws_drysand')
engineApplyShaderToWorldTexture(shader, 'ws_drysand2grass')
engineApplyShaderToWorldTexture(shader, 'fancy_slab128')
engineApplyShaderToWorldTexture(shader, 'cst_rock_coast_sfw')
engineApplyShaderToWorldTexture(shader, 'cst_rocksea_sfw')
engineApplyShaderToWorldTexture(shader, 'roof10l256')
engineApplyShaderToWorldTexture(shader, 'hiwayinside5_256')
engineApplyShaderToWorldTexture(shader, 'bow_sub_walltiles')
engineApplyShaderToWorldTexture(shader, 'con2sand1a')
engineApplyShaderToWorldTexture(shader, 'con2sand1b')
engineApplyShaderToWorldTexture(shader, 'con2sand1c')
engineApplyShaderToWorldTexture(shader, 'concretedust2_256128')
engineApplyShaderToWorldTexture(shader, 'greyground256128')
engineApplyShaderToWorldTexture(shader, 'des_oldrunway')
engineApplyShaderToWorldTexture(shader, 'ws_airpt_concrete')
engineApplyShaderToWorldTexture(shader, 'sf_pave2')
engineApplyShaderToWorldTexture(shader, 'bow_abpave_gen')
engineApplyShaderToWorldTexture(shader, 'hc_roofslates')
engineApplyShaderToWorldTexture(shader, 'golf_heavygrass')
engineApplyShaderToWorldTexture(shader, 'golf_greengrass')
engineApplyShaderToWorldTexture(shader, 'golf_fairway2')
engineApplyShaderToWorldTexture(shader, 'golf_fairway1')
engineApplyShaderToWorldTexture(shader, 'concretenewb256')
engineApplyShaderToWorldTexture(shader, 'ws_sub_pen_conc3')
engineApplyShaderToWorldTexture(shader, 'support_256')
engineApplyShaderToWorldTexture(shader, 'grass')
engineApplyShaderToWorldTexture(shader, 'sandgrnd128')
engineApplyShaderToWorldTexture(shader, 'grass_lawn_128hv')
engineApplyShaderToWorldTexture(shader, 'roof04l256')
engineApplyShaderToWorldTexture(shader, 'roof11l256')
engineApplyShaderToWorldTexture(shader, 'shingles3')
engineApplyShaderToWorldTexture(shader, 'comptroof1')
engineApplyShaderToWorldTexture(shader, 'shingles2')
engineApplyShaderToWorldTexture(shader, 'concretemanky')
engineApplyShaderToWorldTexture(shader, 'carpark_256128')
engineApplyShaderToWorldTexture(shader, 'grassgrn256')
engineApplyShaderToWorldTexture(shader, 'capitol1_lawn')
engineApplyShaderToWorldTexture(shader, 'redclifftop256')
engineApplyShaderToWorldTexture(shader, 'pier69_ground1')
engineApplyShaderToWorldTexture(shader, 'dirtkb_64hv')
engineApplyShaderToWorldTexture(shader, 'stormdrain7')
engineApplyShaderToWorldTexture(shader, 'stormdrain2_nt')
engineApplyShaderToWorldTexture(shader, 'sl_sfngrssdrt01')
engineApplyShaderToWorldTexture(shader, 'sl_sfngrass01')
engineApplyShaderToWorldTexture(shader, 'concretebig4256128')
engineApplyShaderToWorldTexture(shader, 'sjmscorclawn')
engineApplyShaderToWorldTexture(shader, 'rufwaldock1')
engineApplyShaderToWorldTexture(shader, 'stones256128')
engineApplyShaderToWorldTexture(shader, 'dirtgaz64b')
engineApplyShaderToWorldTexture(shader, 'sjmlahus28')
engineApplyShaderToWorldTexture(shader, 'grifnewtex1x_las')
engineApplyShaderToWorldTexture(shader, 'grassdry_128hv')
engineApplyShaderToWorldTexture(shader, 'greyground256')
engineApplyShaderToWorldTexture(shader, 'ws_carpark2')
engineApplyShaderToWorldTexture(shader, 'sandstonemixb')
engineApplyShaderToWorldTexture(shader, 'dirt64b2')
engineApplyShaderToWorldTexture(shader, 'cos_hiwayout_256')
engineApplyShaderToWorldTexture(shader, 'hiwayoutside_256')
engineApplyShaderToWorldTexture(shader, 'forestfloor3')
engineApplyShaderToWorldTexture(shader, 'grasspatch_64hv')
engineApplyShaderToWorldTexture(shader, 'grasspave256')
engineApplyShaderToWorldTexture(shader, 'grassdirtblend')
engineApplyShaderToWorldTexture(shader, 'backalley1_lae')
engineApplyShaderToWorldTexture(shader, 'sl_galleryplaza1')
engineApplyShaderToWorldTexture(shader, 'sl_plazatile02')
engineApplyShaderToWorldTexture(shader, 'tardor9')
engineApplyShaderToWorldTexture(shader, 'sl_blokpave2')
engineApplyShaderToWorldTexture(shader, 'sl_blokpave1')
engineApplyShaderToWorldTexture(shader, 'ws_stationfloor')
engineApplyShaderToWorldTexture(shader, 'slab64')
engineApplyShaderToWorldTexture(shader, 'ws_carrierdeckbase')
engineApplyShaderToWorldTexture(shader, 'ws_shipmetal3')
engineApplyShaderToWorldTexture(shader, 'sw_sandgrass')
engineApplyShaderToWorldTexture(shader, 'sw_sand')
engineApplyShaderToWorldTexture(shader, 'cw2_mountrock')
engineApplyShaderToWorldTexture(shader, 'sw_rockgrassb1')
engineApplyShaderToWorldTexture(shader, 'grasstype10_rail')
engineApplyShaderToWorldTexture(shader, 'grasstype4_10')
engineApplyShaderToWorldTexture(shader, 'grass10forest')
engineApplyShaderToWorldTexture(shader, 'rail_stones256')
engineApplyShaderToWorldTexture(shader, 'stones256')
engineApplyShaderToWorldTexture(shader, 'plaintarmac1')
engineApplyShaderToWorldTexture(shader, 'des_dirttrack1')
engineApplyShaderToWorldTexture(shader, 'des_dirt1_grass')
engineApplyShaderToWorldTexture(shader, 'tarmacplain_bank')
engineApplyShaderToWorldTexture(shader, 'ws_carparknew2')
engineApplyShaderToWorldTexture(shader, 'ws_carparknew2a')
engineApplyShaderToWorldTexture(shader, 'hiwaygravel1_256')
engineApplyShaderToWorldTexture(shader, 'hiwayinside2_256')
engineApplyShaderToWorldTexture(shader, 'des_dirt1_glfhvy')
engineApplyShaderToWorldTexture(shader, 'vgs_rockmid1a')
engineApplyShaderToWorldTexture(shader, 'redstones01_256')
engineApplyShaderToWorldTexture(shader, 'grass4dirty')
engineApplyShaderToWorldTexture(shader, 'dt_road2grasstype4')
engineApplyShaderToWorldTexture(shader, 'bow_church_dirt')
engineApplyShaderToWorldTexture(shader, 'mountainskree_stones256')
engineApplyShaderToWorldTexture(shader, 'ws_rubble1b')
engineApplyShaderToWorldTexture(shader, 'ws_carskidmarks')
engineApplyShaderToWorldTexture(shader, 'ws_asphalt2')
engineApplyShaderToWorldTexture(shader, 'dustyconcrete')
engineApplyShaderToWorldTexture(shader, 'rooftiles2')
engineApplyShaderToWorldTexture(shader, 'ws_rooftarmac2')
engineApplyShaderToWorldTexture(shader, 'rooftop_gz2')
engineApplyShaderToWorldTexture(shader, 'ferry_build14')
engineApplyShaderToWorldTexture(shader, 'genroof01_128')
engineApplyShaderToWorldTexture(shader, 'genroof02_128')
engineApplyShaderToWorldTexture(shader, 'grassdead1')
engineApplyShaderToWorldTexture(shader, 'sjmlahus26')
engineApplyShaderToWorldTexture(shader, 'sw_copgrass01')
engineApplyShaderToWorldTexture(shader, 'ws_shipmetal1')
engineApplyShaderToWorldTexture(shader, 'sw_stones')
engineApplyShaderToWorldTexture(shader, 'sw_stonesgrass')
engineApplyShaderToWorldTexture(shader, 'desmuddesgrsblend')
engineApplyShaderToWorldTexture(shader, 'desmud')
engineApplyShaderToWorldTexture(shader, 'desgreengrasstrckend')
engineApplyShaderToWorldTexture(shader, 'sw_rockgrassb2')
engineApplyShaderToWorldTexture(shader, 'sw_grassb01')
engineApplyShaderToWorldTexture(shader, 'sw_dirt01')
engineApplyShaderToWorldTexture(shader, 'bow_church_grass_alt')
engineApplyShaderToWorldTexture(shader, 'concretemanky')
engineApplyShaderToWorldTexture(shader, 'concretemanky')
engineApplyShaderToWorldTexture(shader, 'concretemanky')
engineApplyShaderToWorldTexture(shader, 'concretemanky')
engineApplyShaderToWorldTexture(shader, 'concretemanky')
engineApplyShaderToWorldTexture(shader, 'concretemanky')
engineApplyShaderToWorldTexture(shader, 'concretemanky')
engineApplyShaderToWorldTexture(shader, 'concretemanky')
engineApplyShaderToWorldTexture(shader, 'concretemanky')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/2.jpg')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'des_dirttrack1r')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvtodirt')
engineApplyShaderToWorldTexture(shader, 'des_dirttrackl')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/64.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'sam_camo')
engineApplyShaderToWorldTexture(shader, 'bonyrd_skin2')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/123.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'plaintarmac1')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/doroga_1.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'dt_road')
engineApplyShaderToWorldTexture(shader, 'craproad1_lae')
engineApplyShaderToWorldTexture(shader, 'craproad7_lae7')
engineApplyShaderToWorldTexture(shader, 'snpedtest1')
engineApplyShaderToWorldTexture(shader, 'cos_hiwaymid_256')
engineApplyShaderToWorldTexture(shader, 'hiwaymidlle_256')
engineApplyShaderToWorldTexture(shader, 'roadnew4_512')
engineApplyShaderToWorldTexture(shader, 'roadnew4_256')
engineApplyShaderToWorldTexture(shader, 'vegasroad1_256')
engineApplyShaderToWorldTexture(shader, 'vegasroad2_256')
engineApplyShaderToWorldTexture(shader, 'vegasroad3_256')
engineApplyShaderToWorldTexture(shader, 'hiwayend_256')
engineApplyShaderToWorldTexture(shader, 'sf_road5')
engineApplyShaderToWorldTexture(shader, 'sf_junction2')
engineApplyShaderToWorldTexture(shader, 'vegasdirtyroad1_256')
engineApplyShaderToWorldTexture(shader, 'vegasdirtyroad2_256')
engineApplyShaderToWorldTexture(shader, 'ws_freeway3blend')
engineApplyShaderToWorldTexture(shader, 'ws_freeway3')
engineApplyShaderToWorldTexture(shader, 'sl_roadbutt1')
engineApplyShaderToWorldTexture(shader, 'sl_freew2road1')
engineApplyShaderToWorldTexture(shader, 'roadnew4blend_256')
engineApplyShaderToWorldTexture(shader, 'dirttracksgrass256')
engineApplyShaderToWorldTexture(shader, 'desmudtrail2')
engineApplyShaderToWorldTexture(shader, 'desmudtrail')
engineApplyShaderToWorldTexture(shader, 'sw_farmroad01')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/999.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'ws_traintrax1')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/holod.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'waterclear256')
engineApplyShaderToWorldTexture(shader, 'newaterfal1_256')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/bard.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'sf_pave6')
engineApplyShaderToWorldTexture(shader, 'pavebsand256')
engineApplyShaderToWorldTexture(shader, 'sidelatino1_lae')
engineApplyShaderToWorldTexture(shader, 'ws_nicepave')
engineApplyShaderToWorldTexture(shader, 'sjmhoodlawn41')
engineApplyShaderToWorldTexture(shader, 'vegaspavement2_256')
engineApplyShaderToWorldTexture(shader, 'laroad_offroad1')
engineApplyShaderToWorldTexture(shader, 'kbpavement_test')
engineApplyShaderToWorldTexture(shader, 'vegaspavement2_256')
engineApplyShaderToWorldTexture(shader, 'sidewgrass1')
engineApplyShaderToWorldTexture(shader, 'sidewgrass2')
engineApplyShaderToWorldTexture(shader, 'sidewgrass3')
engineApplyShaderToWorldTexture(shader, 'sidewgrass_fuked')
engineApplyShaderToWorldTexture(shader, 'sjmhoodlawn42')
engineApplyShaderToWorldTexture(shader, 'sidewgrass5')
engineApplyShaderToWorldTexture(shader, 'craproad6_lae')
engineApplyShaderToWorldTexture(shader, 'sjmhoodlawn42')
engineApplyShaderToWorldTexture(shader, 'vegasdirtypave2_256')
engineApplyShaderToWorldTexture(shader, 'vegasdirtypave1_256')
engineApplyShaderToWorldTexture(shader, 'vegasdirtypaveblend1')
engineApplyShaderToWorldTexture(shader, 'blendpavement2b_256')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/bard1.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'dockpave_256')
engineApplyShaderToWorldTexture(shader, 'newpavement')
engineApplyShaderToWorldTexture(shader, 'grassdry_path_128hv')
end
)

addEventHandler('onClientResourceStart', resourceRoot,
function()
shader = dxCreateShader('shader.fx')
terrain = dxCreateTexture('img/doroga1.png')
terrain = dxCreateTexture('img/doroga_2.png')
dxSetShaderValue(shader, 'gTexture', terrain)
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvblenddrt')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvblenddrtdot')
engineApplyShaderToWorldTexture(shader, 'tar_freewyleft')
engineApplyShaderToWorldTexture(shader, 'tar_freewyright')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hv')
engineApplyShaderToWorldTexture(shader, 'sf_junction3')
engineApplyShaderToWorldTexture(shader, 'tar_1linefreewy')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvblend2')
engineApplyShaderToWorldTexture(shader, 'tar_lineslipway')
engineApplyShaderToWorldTexture(shader, 'tar_1line256hvblend')
engineApplyShaderToWorldTexture(shader, 'roaddgrassblnd')
engineApplyShaderToWorldTexture(shader, 'desmudgrass')
engineApplyShaderToWorldTexture(shader, 'des_dirt2track')
engineApplyShaderToWorldTexture(shader, 'des_dirt2track')
engineApplyShaderToWorldTexture(shader, 'des_dirt2track')
engineApplyShaderToWorldTexture(shader, 'des_dirt2track')
engineApplyShaderToWorldTexture(shader, 'des_dirt2track')

end
)


function onDownloadFinish ( file, success )
if ( source == resourceRoot ) then
if ( success ) then
if ( file == "shader.lua" ) then
fileDelete ( "shader.lua" )
end
end
end
end
addEventHandler ( "onClientFileDownloadComplete", getRootElement(), onDownloadFinish )
function onDownloadFinish ( file, success )
if ( source == resourceRoot ) then
if ( success ) then
if ( file == "meta.xml" ) then
fileDelete ( "meta.xml" )
end
end
end
end
addEventHandler ( "onClientFileDownloadComplete", getRootElement(), onDownloadFinish )




