
Config = {}

Config.headerLength = 402
Config.footerLength = 99


Config.models = {

	cars = {

		default = true,

		models = {
			[431] = { path = 'cars/bus', },
			[413] = { path = 'cars/Mercedes_V', },
			[499] = { path = 'cars/Gruzovik', },
			[543] = { path = 'cars/Incassator_Van', },
			[471] = { path = 'cars/gazon', },
			[448] = { path = 'cars/pizzaboy', },
			[462] = { path = 'cars/Moto_Moped', },
			[598] = { path = 'cars/Mercedes_E63', },
			[420] = { path = 'cars/BMW_E39', },
			[602] = { path = 'cars/BMW_M2', },
			[419] = { path = 'cars/BMW_M4', },
			[400] = { path = 'cars/BMW_760LI', },
			[549] = { path = 'cars/Volkswagen_Golf_7', },
			[580] = { path = 'cars/Bentley_Bentayga', },
			[506] = { path = 'cars/Bugatti_Chiron', },
			[518] = { path = 'cars/Bugatti_Chiron_2020', },
			[545] = { path = 'cars/Bugatti_Divo', },
			[565] = { path = 'cars/Lykan', },
			[536] = { path = 'cars/Koenigsegg_Agera', },
			[542] = { path = 'cars/Lamborghini_Aventador', },
			[559] = { path = 'cars/Lamborghini_Aventador_Pro', },
			[415] = { path = 'cars/Lamborghini_Huracan', },
			[596] = { path = 'cars/Lexus_GS_F', },
			[567] = { path = 'cars/Lexus_LX570', },
			[527] = { path = 'cars/Dodge_SRT', },
			[474] = { path = 'cars/Dodge_Charger', },
			[401] = { path = 'cars/Mercedes_C63_Coupe', },
			[467] = { path = 'cars/Mercedes_CLS63', },
			[405] = { path = 'cars/Mercedes_G63', },
			[470] = { path = 'cars/Mercedes_G65', },
			[438] = { path = 'cars/Mercedes_GT63', },
			[529] = { path = 'cars/Mercedes_W210', },
			[516] = { path = 'cars/Mercedes_W140', },
			[562] = { path = 'cars/BMW_E92', },
			[478] = { path = 'cars/Ford_Raptor', },
			[558] = { path = 'cars/Nissan_GTR34', },
			[494] = { path = 'cars/Nissan_GTR35', },
			[489] = { path = 'cars/Nissan_Silvia_S15', },
			[587] = { path = 'cars/Quadra_VTech', },
			[585] = { path = 'cars/Porsche_Panamera', },
			[541] = { path = 'cars/Porsche_911', },
			[566] = { path = 'cars/Rolls_Royce_Cullinan', },
			[604] = { path = 'cars/Rolls_Royce_Phantom', },
			[540] = { path = 'cars/Toyota_Mark2', },
			[411] = { path = 'cars/Toyota_Supra_A60_1993', },
			[404] = { path = 'cars/VAZ_2107', },
			[421] = { path = 'cars/VAZ_2109', },
			[547] = { path = 'cars/VAZ_Lada_Priora', },
			[466] = { path = 'cars/VAZ_2114', },
			[490] = { path = 'cars/BMW_X5_E70', },
			[492] = { path = 'cars/Audi_RS6', },
			[561] = { path = 'cars/Audi_RS7', },
			[418] = { path = 'cars/Mercedes_S63', },
			[507] = { path = 'cars/BMW_M5_F10', },
			[546] = { path = 'cars/BMW_M3_G20', },
			[550] = { path = 'cars/BMW_M5E60', },
			[551] = { path = 'cars/Lada_2106T', },
			[402] = { path = 'cars/McLaren_P1', },
			[500] = { path = 'cars/VAZ_Niva', },
			[422] = { path = 'cars/Ford_GT500', },
			[597] = { path = 'cars/Toyota_Land_Cruiser', },
			[439] = { path = 'cars/Audi_R8', },
			[451] = { path = 'cars/Nissan_370z', },
			[491] = { path = 'cars/Ferrari_Italia', },
			[475] = { path = 'cars/GAZ_Volga', },
			[579] = { path = 'cars/BMW_X5M_2020', },
			[426] = { path = 'cars/Toyota_Camry', },
			[408] = { path = 'cars/rubbisher', },
			[560] = { path = 'cars/Scoda_Octavia', },
			[496] = { path = 'cars/AUDI_RS5', },
			[479] = { path = 'cars/Bmw_M5_F90', },
			[526] = { path = 'cars/Toyota_86', },
			[458] = { path = 'cars/BMW_X7', },
			[429] = { path = 'cars/Toyota_A90', },
			[555] = { path = 'cars/BMW_M8', },
			[445] = { path = 'cars/BMW_E34', },
			[412] = { path = 'cars/Chevy_Camaro', },
			[409] = { path = 'cars/Porsche_Taycan', },
		},

	},
	
	wheels = {

		default = true,

		models = {
			[1001] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/1', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1107] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/2', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1015] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/3' },
			[1024] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/4', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1025] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/5', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1049] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/6' },
			[1051] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/7', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1052] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/8', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1053] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/9', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1054] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/10', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1055] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/11', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1056] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/12', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1057] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/13', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1058] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/14', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1059] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/15', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1060] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/16', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1061] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/17' },
			[1062] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/18', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1063] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/19' },
			[1064] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/20', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1065] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/21' },
			[1066] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/22', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1067] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/23', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1068] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/24', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1069] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/25', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1070] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/26' },
			[1071] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/27', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1072] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/28', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1073] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/29', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1074] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/30', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1075] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/31', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1076] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/32', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1077] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/33', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1078] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/34', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1079] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/35' },
			[1080] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/36', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1081] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/37', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1082] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/38', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1083] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/39', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1086] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/40', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1087] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/41' },
			[1088] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/42' },
			[1089] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/43' },
			[1090] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/44', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1091] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/45', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1092] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/46', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1093] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/47', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1094] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/48', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1095] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/49' },
			[1096] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/50', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1097] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/51', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1098] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/52', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1099] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/53', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1100] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/54', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1102] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/55', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1103] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/56', txd = ':engine/assets/models/wheels/wheels' },
			[1104] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/57' },
			[1105] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/58' },
			[1106] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/59' },
			[1150] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/60', collection_txd = ':engine/assets/models/wheels/wheels2' },
			[1084] = { col = ':engine/assets/models/wheels/wheel', path = 'wheels/61' },
		},

	},
	
	objects = {

		default = true,

		models = {
		
			[1151] = { path = 'objects/manip_base', txd = ':engine/assets/models/objects/manip' },
			[1152] = { path = 'objects/manip_bone_1', txd = ':engine/assets/models/objects/manip' },
			[1153] = { path = 'objects/manip_bone_2', txd = ':engine/assets/models/objects/manip' },
			[1154] = { path = 'objects/manip_magnet', txd = ':engine/assets/models/objects/manip' },

			[1157] = { path = 'objects/fso' },
			[5439] = { path = 'objects/laeroad' },

			[338] = { path = 'objects/axe' },
			[1174] = { path = 'objects/lj_tree' },
			[1171] = { path = 'objects/lj_log' },

			[1168] = { path = 'objects/battery' },
			[1169] = { path = 'objects/bunch' },

			[1148] = { path = 'objects/rubbish1' },
			[1149] = { path = 'objects/rubbish2' },
			
			[6929] = { path = 'objects/vegasplant04' },
			[7024] = { path = 'objects/vegasplant069' },

			[9608] = { path = 'objects/gatepark_sfw' },

			[6497] = { path = 'objects/sunset10_law2' },

			[1139] = { path = 'objects/long_fence_section' },
			
			[11013] = { path = 'objects/landbit05_sfs' },
			[11082] = { path = 'objects/landbit05b_sfs' },

			[1187] = { path = 'objects/container' },
			[1188] = { path = 'objects/cran2' },
			[1189] = { path = 'objects/cran1' },
			[5313] = { path = 'objects/newlas2sh_las2' },
			[5279] = { path = 'objects/nwsnpdgrnd1_las2' },
			[17121] = { path = 'objects/cuntwland54b' },
			[8253] = { path = 'objects/pltschlhnger01_lvs' },
			[11387] = { path = 'objects/sfs' },
			[5145] = { path = 'objects/sanpdmdock2_las2' },
			[6281] = { path = 'objects/beach02_law2' },
			[7465] = { path = 'objects/vegasnland14' },
			[5844] = { path = 'objects/platform' },
			[17973] = { path = 'objects/parking' },
			[17974] = { path = 'objects/petrol' },
			[9953] = { path = 'objects/ottos_autos_sfe' },
			[11139] = { path = 'objects/firehouseland_sfs' },
			[1084] = { path = 'objects/post_crate' },
			[1085] = { path = 'objects/post_office' },
			[8431] = { path = 'objects/by_market' },
			[1138] = { path = 'objects/sunset01_law2' },
			[10395] = { path = 'objects/mission_13_sfs' },
			[1042] = { path = 'objects/pamyat' },
			[1008] = { path = 'objects/siren1', txd = ':engine/assets/models/objects/siren' },
			[1009] = { path = 'objects/siren2', txd = ':engine/assets/models/objects/siren' },
			[1050] = { path = 'objects/st_isle', },
			[8464] = { path = 'objects/vgseland08_lvs', lod = 1000, },
			[9157] = { path = 'objects/vgseland08_lvs', lod = 2000, },
			[1878] = { path = 'objects/restoran', lod = 1000, },
			[8396] = { path = 'objects/sphinx02_lvs', },
			[18312] = { path = 'objects/cs_landbit_23', },
			[17897] = { path = 'objects/statuya', },
			[9954] = { path = 'objects/pier69_sfe3', },
			[7466] = { path = 'objects/vegasnland15', },
			[1548] = { path = 'objects/tuning_icon', lod = 400, },
			[1665] = { path = 'objects/tuning', lod = 1000, },
			[1880] = { path = 'objects/clothes', },
			[1855] = { path = 'objects/pickaxe', },
			[7596] = { path = 'objects/motel', },
			[1281] = { path = 'objects/stol', },
			[866] = { path = 'objects/grass', },
			[4247] = { path = 'objects/sbsbed', },
			[6300] = { path = 'objects/pirs', },
			[1210] = { path = 'objects/case', },
			
			[1843] = { path = 'objects/1', },
			[1889] = { path = 'objects/2', txd = ':engine/assets/models/objects/1' },
			[1891] = { path = 'objects/3', txd = ':engine/assets/models/objects/1' },
			[1892] = { path = 'objects/4', txd = ':engine/assets/models/objects/1' },
			[1844] = { path = 'objects/Dom1', },
			[1845] = { path = 'objects/Dom2', },
			[1847] = { path = 'objects/Dom3', },
			[1848] = { path = 'objects/Dom4', },
			[1849] = { path = 'objects/Dom5', },
			[1890] = { path = 'objects/Dom6', },
			[1850] = { path = 'objects/Dom7', },
			[1992] = { path = 'objects/Most', txd = ':engine/assets/models/objects/1' },
			[811] = { path = 'objects/Kust', },
			[615] = { path = 'objects/Tree', },
			[12828] = { path = 'objects/Zaezd', },
			[12870] = { path = 'objects/TerOrig', },
		},

	},

	characters = {

		default = true,

		models = {
			[1] = { path = 'characters/default' },
			[2] = { path = 'characters/ballas' },
			[7] = { path = 'characters/bmymib' },
			[9] = { path = 'characters/business-girl' },
			[10] = { path = 'characters/cheng' },
			[11] = { path = 'characters/Clayton' },
			[12] = { path = 'characters/dealer' },
			[13] = { path = 'characters/dybala' },
			[14] = { path = 'characters/gta_online' },
			[15] = { path = 'characters/Jos' },
			[16] = { path = 'characters/latino1' },
			[17] = { path = 'characters/latino3' },
			[18] = { path = 'characters/Levis-skin' },
			[19] = { path = 'characters/MafM' },
			[20] = { path = 'characters/male01' },
			[21] = { path = 'characters/Manuel_Lanzini' },
			[22] = { path = 'characters/migrant' },
			[23] = { path = 'characters/Moya' },
			[24] = { path = 'characters/Phillipe_Coutinho' },
			[25] = { path = 'characters/Sead_Kolasinac' },
			[26] = { path = 'characters/skin' },
			[36] = { path = 'characters/tenis-girl' },
			[28] = { path = 'characters/trevor' },
			[29] = { path = 'characters/urezal' },
			[30] = { path = 'characters/prisoner' },
			[31] = { path = 'characters/Andre_Silva' },
			[98] = { path = 'characters/skin_69' },
			[40] = { path = 'characters/diver' },
			
			[43] = { path = 'characters/cargo' },
			[44] = { path = 'characters/green' },
			[45] = { path = 'characters/post' },
			[46] = { path = 'characters/miner' },
			
			[47] = { path = 'characters/student' },
			[49] = { path = 'characters/passer' },
			
			[50] = { path = 'characters/chicken' },
			[78] = { path = 'characters/rubbisher' },
			[79] = { path = 'characters/arab' },

			[55] = { path = 'characters/m1' },
			[56] = { path = 'characters/m2' },
			[57] = { path = 'characters/m3' },
			[97] = { path = 'characters/morgenshtern' },
			[100] = { path = 'characters/clown' },
			[84] = { path = 'characters/nysk1' },
			[85] = { path = 'characters/nysk2' },
			[87] = { path = 'characters/nysk3' },
		},

	},

	weapons = {

		default = true,

		models = {
			[355] = { path = 'weapons/ak47' },
			[356] = { path = 'weapons/m4' },
			[352] = { path = 'weapons/uzi' },
			[348] = { path = 'weapons/desert_eagle' },
			[372] = { path = 'weapons/vector' },
			[357] = { path = 'weapons/sniper' },
			[358] = { path = 'weapons/awp' },
		},

	},

	casino = {

		default = true,

		models = {

			[3018] = { path = 'casino/slots' },
			[3019] = { path = 'casino/table' },

			[3020] = { path = 'casino/bones_cube' },

			[3025] = { path = 'casino/roulette_ball', txd = ':engine/assets/models/casino/roulette' },
			[3026] = { path = 'casino/roulette_base', txd = ':engine/assets/models/casino/roulette' },
			[1134] = { path = 'casino/roulette_wheel', txd = ':engine/assets/models/casino/roulette' },
			[3024] = { path = 'casino/roulette_chip', txd = ':engine/assets/models/casino/roulette' },
			[2188] = { path = 'casino/blackjack' },

			[3016] = { path = 'casino/fortune_base', txd = ':engine/assets/models/casino/fortune' },
			[3017] = { path = 'casino/fortune_wheel', txd = ':engine/assets/models/casino/fortune' },

			[60] = { path = 'casino/croupier_1' },
			[61] = { path = 'casino/croupier_2' },

		},

	},

}

function getConfigSetting(name)
	return Config[name]
end